services:
  - type: web
    name: gyaan-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: EXA_API_KEY
        sync: false
      - key: PERPLEXITY_API_KEY
        sync: false